### PR TITLE
fix: multipartUpload small file upload by callback data

### LINKED ISSUE #319: 使用4.11.2multipartUpload传小文件时会报json错误
` case 22:
                                return d = {
                                    res: l.res,
                                    bucket: this.options.bucket,
                                    name: e,
                                    etag: l.res.headers.etag
                                },
                                n.headers && n.headers["x-oss-callback"] && (d.data = JSON.parse(l.data.toString())),
                                t.abrupt("return", d);`
在使用multipartUpload上传小于100kb的图片时，上面的JSON.parse(l.data.toString())会报JSON错误，换到4.10.1就没问题了
另外为什么有些版本不能通过http://gosspublic.alicdn.com/aliyun-oss-sdk-4.11.2.min.js获取到，怎么知道哪些版本可以通过这样的url取到呢？谢谢

### PR DESCRIPTION
**Pull request by binghaiwang**
fix multipartUpload small file upload by callback data
Closes #319 and #357

### CODE REVIEW

File: lib/browser/multipart.js [hunk 1]
```diff
@@ -48,11 +48,10 @@ proto.multipartUpload = function* multipartUpload(name, file, options) {
...
       bucket: this.options.bucket,
       name: name,
-      etag: result.res.headers.etag
+      etag: result.res.headers.etag,
+      data: result.data
     };
-    if (options.headers && options.headers['x-oss-callback']) {
-      ret.data = JSON.parse(result.data.toString());
-    }
+
```
Comment (PeterRao) [inline lib/browser/multipart.js]: 和_completeMultipartUpload保持一致的返回数据

Comment (binghaiwang) [reply lib/browser/multipart.js]: done
