### PR TITLE
fix the copy object api bug which can not use non-English source object name

### LINKED ISSUE #139: copy功能的oldname不能是中文
如果是中文会报错
`TypeError: The header content contains invalid characters`

### PR DESCRIPTION
**Pull request by mars-coder**
fix #139
1. fix the copy object api bug which can not use non-English source object name
2. add a test case to test copy api with non-English source object name

### CODE REVIEW

**Comment by mars-coder** [comment]
fix https://github.com/ali-sdk/ali-oss/issues/139

File: lib/object.js [hunk 1]
```diff
@@ -252,8 +252,11 @@ proto.copy = function* copy(name, sourceName, options) {
 
   if (sourceName[0] !== '/') {
     // copy same bucket object
```
Comment (baiyubin) [inline lib/object.js]: // copy same bucket object 应该是 // no specify  bucket name

Comment (mars-coder) [inline lib/object.js]: 好的，马上修改
