### PR TITLE
fix: the multipartUpload return value has same structure

### LINKED ISSUE #282: multipartUpload 返回不一致, 找不到原因
请问各位大神，我使用  multipartUpload 为什么感觉，每次的返回结果不一致啊。我是浏览器环境。
```javascript
  const handleFileUpload = (field, files) => {
    if (!files || !files.length) return undefined;

    const today = (new Date()).valueOf();
    const fileMap = {};

// 这里组装出 multipartUpload 多个数组，为了实现多个文件上传
    const funcs = _.map(files, (file) => {
      const fname = file.name.replace(/([^.]+)$/, `${today}.$1`);
      const key = `${field}/${fname}`;
      fileMap[key] = file.name;
      return props.oss.multipartUpload(key, file);
    });

    return window.Promise.all(funcs)
      .then(xs => xs.map(x => console.log('--upload--', x) && ({ FileName: fileMap[x.name], AttachPath: x.url })));
  };
```

下面是  console 的结果
```
--upload--
Object {name: "images/89624aca55e...

name: "images/89624aca55ef17fbc034c9352582765c.1502246519052.jpg"

res: Object

url: "http://jincheng-posts.oss-cn-shanghai.aliyuncs.com/images/89624aca55ef17fbc034c9352582765c.1502246519052.jpg"

__proto__: Object


--upload--
Object {res: {status: 200, status...

bucket: "jincheng-posts"

etag: ""DD49043F622CC9AFACA23682551855B5-1""

name: "images/0d0af432431aad8149ff59969cc70557.1502246587450.jpg"

res: Object
__proto__: Object
```

第一次返回的 json 有  name, url, res 属性，但是第二次却是 bucket，etag, name, res

而且这两次结果跟官网的说明都不一致  [https://help.aliyun.com/document_detail/31992.html](https://help.aliyun.com/document_detail/31992.html)

### PR DESCRIPTION
**Pull request by PeterRao**
fix: the multipartUpload return value has same object

when file size is small then minPartSize, the multipartUpload methods also return ‘bucket’、‘name’、‘etag’

Closes #282

### CODE REVIEW

**Comment by fengmk2** [comment]
跟 master rebase 一下代码。然后 commit log 写具体内容，而不是 fix issue

**Comment by PeterRao** [comment]
@fengmk2 改了下，辛苦在review下。

File: lib/browser/multipart.js [hunk 1]
```diff
@@ -44,7 +44,12 @@ proto.multipartUpload = function* multipartUpload(name, file, options) {
       yield options.progress(1);
     }
 
-    return ret;
+    return {
+      res: ret.res,
+      bucket: this.options.bucket,
+      name: name,
+      etag: ret.res.headers.etag
```
Comment (fengmk2) [inline lib/browser/multipart.js]: https://github.com/PeterRao/ali-oss/blob/c97e36aa2cfbb436b51d2f0fa3a7a9783dac27ac/lib/browser/multipart.js#L295 原来还会有一个 data 字段

Comment (PeterRao) [reply lib/browser/multipart.js]: ok，加上了

**Comment by fengmk2** [comment]
+1

明天本地跑一下单测，过了合并发布。

**Comment by fengmk2** [comment]
4.11.2
